CMAKE_MINIMUM_REQUIRED(VERSION 3.0)

# CREATE_NAMED_BENCHMARK(foo bar.cc) creates a benchmark named `foo` from the
# file `bar.cc`.
MACRO(CREATE_NAMED_BENCHMARK NAME FILENAME)
    ADD_EXECUTABLE(${NAME} ${FILENAME})
    ADD_TEST(NAME ${NAME} COMMAND ${NAME})
    SET_TESTS_PROPERTIES(${NAME} PROPERTIES LABELS "BENCHMARK")
    TARGET_LINK_LIBRARIES(${NAME}
        benchmark
        glog
        pthread)
    ADD_DEPENDENCIES(${NAME}
        ${GOOGLEBENCHMARK_PROJECT}
        ${GOOGLELOG_PROJECT})
ENDMACRO(CREATE_NAMED_BENCHMARK)

# CREATE_BENCHMARK(foo) creates a benchmark named `foo` from the file `foo.cc`.
MACRO(CREATE_BENCHMARK NAME)
    CREATE_NAMED_BENCHMARK(${NAME} ${NAME}.cc)
ENDMACRO(CREATE_BENCHMARK)
